### ISSUE TITLE
cef binaries not found even if using repo

### ISSUE THREAD

**Issue by erdalkaraca** [maketechnology/chromium.swt#23]
I think I have included all relevant bundles from the CEF binaries repo, but still getting this exception:

java.lang.UnsatisfiedLinkError: Could not find resourcecef.pak (in subdirectory: chromium-3071 )
	at org.eclipse.swt.internal.chromium.ResourceExpander.findResource(ResourceExpander.java:116)
	at org.eclipse.swt.chromium.Chromium.loadLib(Chromium.java:479)
	at org.eclipse.swt.chromium.Chromium.<clinit>(Chromium.java:50)
	at org.eclipse.swt.chromium.Browser.<init>(Browser.java:32)

I am on win10 x86_64.

**Comment by gzunino** [comment]
Hi, thanks for the report, I think is due #18. We will deliver new version in the next days.

**Comment by erdalkaraca** [comment]
Yes, just tried out the patch described in #18 in the debugger and the Browser initializes successfully and loads the page.
