### ISSUE TITLE
NPE when creating a browser

### ISSUE THREAD

**Issue by vladdu** [maketechnology/chromium.swt#32]
I'm not sure this is the right place to report, but I get the exception below when trying to instantiate a Chromium browser (with fBrowser = new Browser(parent, SWT.NONE);). Is it anything I am doing wrong?

java.lang.NullPointerException
	at jnr.ffi.provider.converters.StructByReferenceFromNativeConverter.fromNative(StructByReferenceFromNativeConverter.java:54)
	at jnr.ffi.provider.converters.StructByReferenceFromNativeConverter.fromNative(StructByReferenceFromNativeConverter.java:33)
	at jnr.ffi.provider.jffi.NativeClosureProxy$$impl$$2.invoke(Unknown Source)
	at com.kenai.jffi.Foreign.invokeArrayO2Int32(Native Method)
	at com.kenai.jffi.Invoker.invokeArrayWithObjectsInt32(Invoker.java:2162)
	at com.kenai.jffi.Invoker.invokeInt(Invoker.java:1942)
	at org.eclipse.swt.chromium.Chromium$Lib$jnr$ffi$0.cefswt_init(Unknown Source)
	at org.eclipse.swt.chromium.Chromium.initCEF(Chromium.java:238)
	at org.eclipse.swt.chromium.Chromium.create(Chromium.java:172)
	at org.eclipse.swt.chromium.Browser.<init>(Browser.java:35)

**Comment by vladdu** [comment]
Oh, I also found this:

(Chromium.java:237) : cefrust.path: C:\Users\vladd\.swt\lib\win32\x86_64\chromium-3071
DLL init
subp: "C:\\Users\\vladd\\.swt\\lib\\win32\\x86_64\\chromium-3071\\chromium_subp-0700.exe"
Calling cef_initialize
[1201/220605.036:ERROR:main_delegate.cc(714)] Could not load cef_extensions.pak

I see that in other contexts this is not a problem, but it might here...

**Comment by webfolderio** [comment]
it works for me on windows 10 & java 11

What is your setup?

**Comment by vladdu** [comment]
Win10 and java 8.

**Comment by gzunino** [comment]
@vladdu @jhbruhn I can't reproduce. Could you please post the versions of jnr bundles being used?

Also, please try with the following versions:
![selection_106](https://user-images.githubusercontent.com/2495175/50402768-ba52c500-0777-11e9-88da-50d7c11f2bec.png)

Thanks.

**Comment by hmarchadour** [comment]
In deed, it works  with the jnr version embedded with eclipse photon, but does not work with eclipse oxygen.

**Comment by vladdu** [comment]
Right, I had a weird target file. It works with a clean photon one. Thanks for the pointer.
