### ISSUE TITLE
Error on Linux "No more handles"

### ISSUE THREAD

**Issue by PhaserEditor2D** [maketechnology/chromium.swt#60]
Hi,

I tested this plugin (0.9.0) on Linux with Photon 2019-03. I just created a simple view with a browser, and when I open the view it shows following error. The errors appear all the time while the view is active. 

```
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4725)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.SWT.error(SWT.java:4585)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:530)
	at org.eclipse.swt.widgets.Control.drawBackground(Control.java:219)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6751)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6035)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4135)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1407)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1584)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4577)
	at org.eclipse.ui.statushandlers.WorkbenchErrorHandler.showStatusAdapter(WorkbenchErrorHandler.java:89)
	at org.eclipse.ui.statushandlers.WorkbenchErrorHandler.handle(WorkbenchErrorHandler.java:52)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler.handle(IDEWorkbenchErrorHandler.java:105)
	at org.eclipse.ui.internal.WorkbenchErrorHandlerProxy.handle(WorkbenchErrorHandlerProxy.java:34)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:216)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:263)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:274)
	at org.eclipse.ui.application.WorkbenchAdvisor.eventLoopException(WorkbenchAdvisor.java:333)
	at org.eclipse.ui.internal.Workbench$1.eventLoopException(Workbench.java:490)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.handle(PartRenderingEngine.java:1195)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1185)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at phasereditor.ide.ModifiedIDEApplication.start(ModifiedIDEApplication.java:179)
	at phasereditor.ide.intro.PhaserIDE2.start(PhaserIDE2.java:75)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)
```

**Comment by gzunino** [comment]
Hi, I don't see anything browser related on that stacktrace. Could you share stdout, the entire stacktrace or anything that can help?

**Comment by PhaserEditor2D** [comment]
This is the stdout:

```
cefrust.path: /home/arian/.swt/lib/linux/x86_64/chromium-3071
DLL init
subp: "/home/arian/.swt/lib/linux/x86_64/chromium-3071/chromium_subp-0900"
Calling cef_initialize
IN SUBP
Calling cef_execute_process
J1:main:OnContextInitialized empty-url
J1:main:initCef Done empty-url
IN SUBP
Calling cef_execute_process
J1:main:paintControl empty-url
create_browser in 140706186260368
parent 39848422
Calling cef_browser_host_create_browser
J1:main:on_after_created jnr.ffi.provider.jffi.DirectMemoryIO[address=0x7ff8b4693990] (about:blank)
J1:main:STARTING MSG LOOP (about:blank)
J1:main:on_after_created handling jnr.ffi.provider.jffi.DirectMemoryIO[address=0x7ff8b4693990] (about:blank)
J1:main:on_loading_state_change 1 (about:blank)
J1:main:update text (about:blank)
J1:main:CALLBACK OnSetFocus FOCUS_SOURCE_NAVIGATION (about:blank)

!ENTRY org.eclipse.ui 4 0 2019-04-25 21:57:20.003
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4725)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.SWT.error(SWT.java:4585)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:530)
	at org.eclipse.swt.widgets.Control.drawBackground(Control.java:219)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6751)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6035)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4135)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1407)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1584)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4577)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at phasereditor.ide.ModifiedIDEApplication.start(ModifiedIDEApplication.java:179)
	at phasereditor.ide.intro.PhaserIDE2.start(PhaserIDE2.java:75)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)

!ENTRY org.eclipse.ui 4 0 2019-04-25 21:57:20.005
!MESSAGE Error occurred during status handling
!STACK 0
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4725)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.SWT.error(SWT.java:4585)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:530)
	at org.eclipse.swt.widgets.Control.drawBackground(Control.java:219)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6751)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6035)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4135)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1407)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1584)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4577)
	at org.eclipse.ui.statushandlers.WorkbenchErrorHandler.showStatusAdapter(WorkbenchErrorHandler.java:89)
	at org.eclipse.ui.statushandlers.WorkbenchErrorHandler.handle(WorkbenchErrorHandler.java:52)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler.handle(IDEWorkbenchErrorHandler.java:105)
	at org.eclipse.ui.internal.WorkbenchErrorHandlerProxy.handle(WorkbenchErrorHandlerProxy.java:34)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:216)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:263)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:274)
	at org.eclipse.ui.application.WorkbenchAdvisor.eventLoopException(WorkbenchAdvisor.java:333)
	at org.eclipse.ui.internal.Workbench$1.eventLoopException(Workbench.java:490)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.handle(PartRenderingEngine.java:1195)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1185)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at phasereditor.ide.ModifiedIDEApplication.start(ModifiedIDEApplication.java:179)
	at phasereditor.ide.intro.PhaserIDE2.start(PhaserIDE2.java:75)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)
J1:main:!on_address_change to about:blank main (about:blank)
J1:main:on_loading_state_change 0 (about:blank)
J1:main:update text (about:blank)
J1:main:on_title_change: about:blank (about:blank)
J1:main:text visited completed (about:blank)
J:delaying shutdown due browsers not disposed yet
```

**Comment by PhaserEditor2D** [comment]
By the way, the same code works on Windows 10.

**Comment by gzunino** [comment]
Please retry with 0.9.1 as there were problems with 0.9.0 linux binaries

**Comment by PhaserEditor2D** [comment]
Same error, same behavior with 0.9.1. These are the used plugins:

```
com.make.chromium.cef.gtk.linux.x86_64_0.4.0.201904250337.jar
org.eclipse.swt.chromium_0.9.1.201904260302.jar
org.eclipse.swt.chromium.gtk.linux.x86_64_0.9.1.201904260302.jar
```

**Comment by dschaefer** [comment]
I get the same thing. Ubuntu 18.04. I'm also seeing errors loading cef_extensions.pak.

[0426/110003.960075:ERROR:main_delegate.cc(714)] Could not load cef_extensions.pak

**Comment by dschaefer** [comment]
Actually, I get the cef_extensions.pak message on Mac too but the browser comes up there.

**Comment by gzunino** [comment]
cef_extensions.pak message is expected, should be a warn, not an error.

I'll do some testing on different linux and gtk versions. Could you all report GTK version and OS, please?

**Comment by PhaserEditor2D** [comment]
>  Could you all report GTK version and OS, please?

```
org.eclipse.swt.internal.deviceZoom=100
org.eclipse.swt.internal.gdk.backend=x11
org.eclipse.swt.internal.gtk.theme=Ambiance
org.eclipse.swt.internal.gtk.version=3.22.30
org.eclipse.swt.internal.webkitgtk.version=2.24.


Ubuntu 18.04.2 LTS
Linux 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64
```

**Comment by dschaefer** [comment]
Mine is the same. gtk 3.22.30 on the latest Ubuntu 18.04.

**Comment by tomvdbussche** [comment]
I'm also having the same issue on Linux, Windows seems to work fine.

Linux 5.1.15-300.fc30.x86_64 (Fedora 30)
GTK 3.24.8-1

```
cefrust.path: /home/tom/.swt/lib/linux/x86_64/chromium-3071
DLL init
subp: "/home/tom/.swt/lib/linux/x86_64/chromium-3071/chromium_subp-0901"
Calling cef_initialize
[0708/162423.336185:ERROR:main_delegate.cc(714)] Could not load cef_extensions.pak
IN SUBP
Calling cef_execute_process
[0708/162423.377910:ERROR:main_delegate.cc(714)] Could not load cef_extensions.pak
J1:main:OnContextInitialized empty-url
J1:main:initCef Done empty-url
IN SUBP
Calling cef_execute_process
[0708/162423.439438:ERROR:main_delegate.cc(714)] Could not load cef_extensions.pak
[0708/162423.468059:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process. 
J1:main:paintControl empty-url
create_browser in 140550689106752
parent 54529688
Calling cef_browser_host_create_browser
J1:main:on_after_created jnr.ffi.provider.jffi.DirectMemoryIO[address=0x7fd4819ba030] (about:blank)
J1:main:STARTING MSG LOOP (about:blank)
J1:main:on_after_created handling jnr.ffi.provider.jffi.DirectMemoryIO[address=0x7fd4819ba030] (about:blank)
J1:main:on_loading_state_change 1 (about:blank)
J1:main:update text (about:blank)
J1:main:CALLBACK OnSetFocus FOCUS_SOURCE_NAVIGATION (about:blank)

(Eclipse:29915): Gdk-CRITICAL **: 16:24:23.560: The window 0x7fd481e64e30 already has a drawing context. You cannot call gdk_window_begin_draw_frame() without calling gdk_window_end_draw_frame() first.
[0708/162423.560862:ERROR:browser_main_loop.cc(256)] Gdk: gdk_drawing_context_get_cairo_context: assertion 'GDK_IS_DRAWING_CONTEXT (context)' failed
[0708/162423.619313:ERROR:buffer_manager.cc(453)] [.DisplayCompositor-0x7fd48187c8c0]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

(Eclipse:29915): Gdk-CRITICAL **: 16:24:23.717: The window 0x7fd481e64e30 already has a drawing context. You cannot call gdk_window_begin_draw_frame() without calling gdk_window_end_draw_frame() first.
[0708/162423.717596:ERROR:browser_main_loop.cc(256)] Gdk: gdk_drawing_context_get_cairo_context: assertion 'GDK_IS_DRAWING_CONTEXT (context)' failed

!ENTRY org.eclipse.ui 4 0 2019-07-08 16:24:23.720
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4725)
	at org.eclipse.swt.SWT.error(SWT.java:4614)
	at org.eclipse.swt.SWT.error(SWT.java:4585)
	...
```

**Comment by jimmybirrias** [comment]
I am getting similar issue in Centos 8, I create a view and I try to create an instance from the Browser but I got this error when I try to open the view
 fatal error has been detected by the Java Runtime Environment:
 SIGSEGV (0xb) at pc=0x00007f6f02aaa85f, pid=12329, tid=0x00007f6f6430c700
JRE version: Java(TM) SE Runtime Environment (8.0_241-b07) (build 1.8.0_241-b07)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.241-b07 mixed mode linux-amd64 compressed oops)
Problematic frame:
C  [libchromium_swt_0102.so+0x8285f]  cefswt_create_browser+0x4f
Here is the full log
[hs_err_pid12329.log](https://github.com/maketechnology/chromium.swt/files/4396275/hs_err_pid12329.log)
Is there any update?
