### ISSUE TITLE
macOS Java8 UnsatisfiedLinkError

### ISSUE THREAD

**Issue by quaeler** [maketechnology/chromium.swt#98]
I am launching a simple RCP (made just to test an EditorPart housing a chromium Browser instance) from Eclipse Oxygen, using Oracle's 1.8.0_181, under macOS 10.13.6.

I fetch the CEF binaries and Chromium plugin from the two maketechnology.io p2 update sites, and have verified that the macOS specific binary plugin exists:
```
algebraic:.metadata loki$ jar tvf ./.plugins/org.eclipse.pde.core/.bundle_pool/plugins/com.make.chromium.cef.cocoa.macosx.x86_64_0.4.0.201908130254.jar
   520 Tue Aug 13 02:54:52 PDT 2019 META-INF/MANIFEST.MF
     0 Tue Aug 13 02:54:52 PDT 2019 META-INF/
     0 Tue Aug 13 02:52:24 PDT 2019 chromium-3071/
     0 Tue Aug 13 02:52:24 PDT 2019 chromium-3071/Chromium Embedded Framework.framework/
     0 Tue Aug 13 02:52:24 PDT 2019 chromium-3071/Chromium Embedded Framework.framework/Resources/
     0 Tue Aug 13 02:52:24 PDT 2019 chromium-3071/Chromium Embedded Framework.framework/Resources/en.lproj/
     0 Tue Aug 13 02:54:52 PDT 2019 META-INF/maven/
     0 Tue Aug 13 02:54:52 PDT 2019 META-INF/maven/com.make/
     0 Tue Aug 13 02:54:52 PDT 2019 META-INF/maven/com.make/com.make.chromium.cef.cocoa.macosx.x86_64/
  1113 Tue Aug 13 02:52:24 PDT 2019 chromium-3071/Chromium Embedded Framework.framework/Resources/Info.plist
239010 Tue Aug 13 02:52:24 PDT 2019 chromium-3071/Chromium Embedded Framework.framework/Resources/natives_blob.bin
391479 Tue Aug 13 02:52:24 PDT 2019 chromium-3071/Chromium Embedded Framework.framework/Resources/cef_200_percent.pak
1558752 Tue Aug 13 02:52:24 PDT 2019 chromium-3071/Chromium Embedded Framework.framework/Resources/snapshot_blob.bin
5925790 Tue Aug 13 02:52:24 PDT 2019 chromium-3071/Chromium Embedded Framework.framework/Resources/cef.pak
184662 Tue Aug 13 02:52:24 PDT 2019 chromium-3071/Chromium Embedded Framework.framework/Resources/en.lproj/locale.pak
284569 Tue Aug 13 02:52:24 PDT 2019 chromium-3071/Chromium Embedded Framework.framework/Resources/cef_100_percent.pak
10130560 Tue Aug 13 02:52:24 PDT 2019 chromium-3071/Chromium Embedded Framework.framework/Resources/icudtl.dat
112388704 Tue Aug 13 02:52:24 PDT 2019 chromium-3071/Chromium Embedded Framework.framework/Chromium Embedded Framework
   760 Tue Aug 13 02:52:26 PDT 2019 chromium-3071/chromium.properties
   908 Tue Aug 13 02:53:42 PDT 2019 META-INF/maven/com.make/com.make.chromium.cef.cocoa.macosx.x86_64/pom.xml
   143 Tue Aug 13 02:54:52 PDT 2019 META-INF/maven/com.make/com.make.chromium.cef.cocoa.macosx.x86_64/pom.properties
algebraic:.metadata loki$ popd
```

I blow away `~/.swt` just to be safe prior to launching. Upon trying to instantiate the browser, i get the following exception:
```
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.e4.ui.workbench.swt".
!STACK 0
java.lang.UnsatisfiedLinkError: Could not find resource libchromium_swt_0102.dylib (in subdirectory: chromium-3071 )
	at org.eclipse.swt.internal.chromium.ResourceExpander.findResource(ResourceExpander.java:119)
	at org.eclipse.swt.chromium.Chromium.loadLib(Chromium.java:1649)
	at org.eclipse.swt.chromium.Chromium.<clinit>(Chromium.java:103)
	at org.eclipse.swt.chromium.Browser.<init>(Browser.java:32)
	at st.theori.eclipse.chro.Editor.createPartControl(Editor.java:49)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:151)
...
```

I can see that the directory structure under `.swt` was created, but never populated:
```
algebraic:~ loki$ ls .swt/lib/macosx/x86_64/chromium-3071/
total 0
drwxr-xr-x  2 loki  staff  64 Dec 29 12:55 .
drwxr-xr-x  3 loki  staff  96 Dec 29 12:55 ..
algebraic:~ loki$ 
```

Is this a known issue? an unknown issue but seemingly not my error? my error?

**Comment by quaeler** [comment]
This seems likely the rose that is #94 by another name.

**Comment by quaeler** [comment]
Cloning this repository and copying the dylibs LFS'd in this repository into the appropriate `~/.swt/` location produces a different error:
```
java.lang.UnsatisfiedLinkError: /Users/loki/.swt/lib/macosx/x86_64/chromium-3071/libchromium_swt_0102.dylib: dlopen(/Users/loki/.swt/lib/macosx/x86_64/chromium-3071/libchromium_swt_0102.dylib, 1): Library not loaded: @loader_path/Chromium Embedded Framework.framework/Chromium Embedded Framework
  Referenced from: /Users/loki/.swt/lib/macosx/x86_64/chromium-3071/libchromium_swt_0102.dylib
  Reason: Incompatible library version: libchromium_swt_0102.dylib requires version 31649.11.255 or later, but Chromium Embedded Framework provides version 783.0.9
```

**Comment by quaeler** [comment]
... and this was because i had downloaded a too-new version of the CEF build from Spotify - fetching the READ me specified 3.3071 (technically `07/19/2017 - CEF 3.3071.1649.g98725e6 / Chromium 59.0.3071.109`) and copying the `Release` framework plugin to be peer to the the dylib files gets the whole thing working.

It's unclear why the .p2 plugins were not obviating my need to do this local install by hand - but at least i have something working now.
